from enum import StrEnum


class CreativeApprovalStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ArtifactCurrencyStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    MISSING = "MISSING"
    BLOCKED = "BLOCKED"


class RuntimeTaskStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    CANCELLING = "CANCELLING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class CandidateSelectionStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    REJECTED = "REJECTED"
    SELECTED = "SELECTED"


class GenerationLifecycleStatus(StrEnum):
    GENERATED = "GENERATED"
    FAILED = "FAILED"


class ReadinessState(StrEnum):
    READY = "READY"
    BLOCKED = "BLOCKED"


class ContentBasisType(StrEnum):
    FACTUAL = "FACTUAL"
    NARRATIVE = "NARRATIVE"
    ADAPTATION = "ADAPTATION"


class ProductionMethod(StrEnum):
    REUSE = "REUSE"
    STOCK = "STOCK"
    SCREEN_CAPTURE = "SCREEN_CAPTURE"
    DETERMINISTIC = "DETERMINISTIC"
    GENERATED_IMAGE = "GENERATED_IMAGE"
    GENERATED_VIDEO = "GENERATED_VIDEO"
    COMPOSITE = "COMPOSITE"


class ProductionBindingTarget(StrEnum):
    SCENE = "SCENE"
    SHOT = "SHOT"


class ProductionBindingRole(StrEnum):
    CHARACTER = "CHARACTER"
    LOCATION = "LOCATION"
    PROP = "PROP"
    WARDROBE = "WARDROBE"
    VOICE = "VOICE"
    STYLE = "STYLE"
    SOURCE_FOOTAGE = "SOURCE_FOOTAGE"
    OPENING_FRAME = "OPENING_FRAME"
    ENDING_FRAME = "ENDING_FRAME"
    PREVIOUS_SHOT = "PREVIOUS_SHOT"


class ProvenanceActor(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"
    IMPORT = "IMPORT"


class ReviewerType(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class DirectorKind(StrEnum):
    OPENMONTAGE = "OPENMONTAGE"
    TAKE = "TAKE"
    ARCREEL_NATIVE = "ARCREEL_NATIVE"


class DirectorFailureClass(StrEnum):
    ROUTE_UNAVAILABLE = "ROUTE_UNAVAILABLE"
    TRANSIENT_EXECUTION_FAILURE = "TRANSIENT_EXECUTION_FAILURE"
    CONTRACT_OR_SEMANTIC_FAILURE = "CONTRACT_OR_SEMANTIC_FAILURE"
    PARTIAL_OR_AMBIGUOUS_EXECUTION = "PARTIAL_OR_AMBIGUOUS_EXECUTION"


class IdentityStrength(StrEnum):
    LOCKED = "LOCKED"
    PREFERRED = "PREFERRED"
    ADVISORY = "ADVISORY"


class IdentityScopeType(StrEnum):
    PROJECT = "PROJECT"
    FORMAT = "FORMAT"
    EPISODE = "EPISODE"
    SEQUENCE = "SEQUENCE"
    SCENE = "SCENE"
    SHOT = "SHOT"


class ResolvedIdentityStatus(StrEnum):
    RESOLVED = "RESOLVED"
    CONFLICTED = "CONFLICTED"


class CapabilitySupport(StrEnum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"


class CapabilityAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


class ExecutionType(StrEnum):
    LOCAL = "LOCAL"
    LOCAL_GPU = "LOCAL_GPU"
    API = "API"
    HYBRID = "HYBRID"


class ObservationExpiryBehavior(StrEnum):
    REVALIDATE = "REVALIDATE"
    BECOME_UNKNOWN = "BECOME_UNKNOWN"


class ExecutionIdentityStability(StrEnum):
    IMMUTABLE_REVISION = "IMMUTABLE_REVISION"
    VERSIONED_ALIAS = "VERSIONED_ALIAS"
    MUTABLE_ALIAS = "MUTABLE_ALIAS"
    UNKNOWN = "UNKNOWN"


class AdmissionOutcome(StrEnum):
    ADMITTED = "ADMITTED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    DENIED_NOT_READY = "DENIED_NOT_READY"
    DENIED_NO_CAPABILITY = "DENIED_NO_CAPABILITY"
    DENIED_UNAVAILABLE = "DENIED_UNAVAILABLE"
    DENIED_BUDGET = "DENIED_BUDGET"
    DENIED_POLICY = "DENIED_POLICY"


class RetryDisposition(StrEnum):
    NOT_RETRYABLE = "NOT_RETRYABLE"
    RETRY_SAME_EXECUTION = "RETRY_SAME_EXECUTION"
    RETRY_WITH_BACKOFF = "RETRY_WITH_BACKOFF"
    NEW_EXECUTION_DECISION_REQUIRED = "NEW_EXECUTION_DECISION_REQUIRED"
    NEW_METHOD_DECISION_REQUIRED = "NEW_METHOD_DECISION_REQUIRED"
    HUMAN_ACTION_REQUIRED = "HUMAN_ACTION_REQUIRED"


class FailureDomain(StrEnum):
    DIRECTOR = "DIRECTOR"
    READINESS = "READINESS"
    METHOD = "METHOD"
    CAPABILITY = "CAPABILITY"
    ADMISSION = "ADMISSION"
    COMPILATION = "COMPILATION"
    EXECUTION = "EXECUTION"
    HOST = "HOST"
    VALIDATION = "VALIDATION"
    INTEGRITY = "INTEGRITY"


class FailureClassification(StrEnum):
    EXPECTED_BLOCK = "EXPECTED_BLOCK"
    TRANSIENT = "TRANSIENT"
    PERMANENT = "PERMANENT"
    CONTRACT = "CONTRACT"
    INTEGRITY = "INTEGRITY"
